name: fleet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  bcrypt: ^1.1.3
  flutter:
    sdk: flutter
  http: ^1.2.2
  postgres: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Inter_24pt-ExtraBold.ttf
    - assets/fonts/Inter_24pt-Regular.ttf
    - assets/fonts/Inter_24pt-ExtraLight.ttf
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
          weight: 100