name: fleet
description: "Fleet Project Management Tool"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  audioplayers: ^6.1.0
  bcrypt: ^1.1.3
  camera_windows: ^0.2.5+1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  postgres: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Inter_24pt-ExtraBold.ttf
    - assets/fonts/Inter_24pt-Regular.ttf
    - assets/fonts/Inter_24pt-ExtraLight.ttf
    
    - assets/audio/siren.mp3
    - assets/audio/android_ringtone.mp3
    - assets/audio/success.mp3

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
          weight: 100